giornate: main.o listaGiornate.o
	gcc -g -o giornate main.o listaGiornate.o

main.o: main.c listaGiornate.h
	gcc -c -g main.c

listaGiornate.o: listaGiornate.c listaGiornate.h
	gcc -c -g listaGiornate.c